# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'SkyWay-Handson-iOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
  pod 'SkyWay'
  # Pods for SkyWay-Handson-iOS

end
